services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
       
      - ./frontend/public:/app/../frontend/public
       
      - ./backend/Database:/app/Database:rw
    working_dir: /app
    environment:
      - DOCKER_ENV=true

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"